# Generated by Django 5.2 on 2025-06-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pruebas', '0002_prueba_descrp_breve_prueba_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Digitos',
            fields=[
                ('prueba_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Pruebas.prueba')),
            ],
            bases=('Pruebas.prueba',),
        ),
    ]
