# Generated by Django 5.2 on 2025-05-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Icono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("archivo", models.FileField(upload_to="iconos/")),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("figura", "Figura"),
                            ("numero", "Número"),
                            ("extras", "Extras"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
