# Generated by Django 5.2 on 2025-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pruebas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prueba",
            name="descrp_breve",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Breve descripción de la prueba",
            ),
        ),
        migrations.AddField(
            model_name="prueba",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="imgPruebas/"),
        ),
    ]
