# Generated by Django 5.2 on 2025-05-08 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconNumber',
            fields=[
                ('icono_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Iconos.icono')),
            ],
            bases=('Iconos.icono',),
        ),
    ]
