# Generated by Django 5.2 on 2025-05-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconos', '0002_iconnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='icono',
            name='categoria',
            field=models.CharField(blank=True, choices=[('figura', 'Figura'), ('numero', 'Número')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='IconNumber',
        ),
    ]
