# Generated by Django 5.2 on 2025-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iconos', '0003_icono_categoria_delete_iconnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icono',
            name='categoria',
            field=models.CharField(blank=True, choices=[('figura', 'Figura'), ('numero', 'Número'), ('extras', 'Extras')], max_length=50, null=True),
        ),
    ]
