# Generated by Django 5.2 on 2025-05-05 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleVisual',
            fields=[
                ('prueba_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Pruebas.prueba')),
            ],
            bases=('Pruebas.prueba',),
        ),
        migrations.CreateModel(
            name='PuzzleScore',
            fields=[
                ('puntajepruebas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Pruebas.puntajepruebas')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PuzzlesVisuales.puzzlevisual')),
            ],
            bases=('Pruebas.puntajepruebas',),
        ),
    ]
