# Generated by Django 5.2 on 2025-04-24 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategoria', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoria')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la prueba')),
                ('tutorial', models.CharField(max_length=350, null=True, verbose_name='Tutorial de la prueba')),
                ('game_url', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL del juego')),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pruebas.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PuntajePruebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
